project:
  type: website
  output-dir: _site

website:
  title: "算法训练营笔记"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Note 1 - 10"
        menu:
          - href: note/day1.qmd
            text: Day 1
          - href: note/day2.qmd
            text: Day 2
          - href: note/day3.qmd
            text: Day 3
          - href: note/day4.qmd
            text: Day 4
          - href: note/day6.qmd
            text: Day 6
          - href: note/day7.qmd
            text: Day 7
          - href: note/day8.qmd
            text: Day 8
          - href: note/day9.qmd
            text: Day 9
          - href: note/day10.qmd
            text: Day 10
      - text: "Note 11 - 20"
        menu:
          - href: note/day11.qmd
            text: Day 11
          - href: note/day13.qmd
            text: Day 13
          - href: note/day14.qmd
            text: Day 14
          - href: note/day15.qmd
            text: Day 15
          - href: note/day16.qmd
            text: Day 16
          - href: note/day17.qmd
            text: Day 17
          - href: note/day18.qmd
            text: Day 18
          - href: note/day20.qmd
            text: Day 20
      - text: "Note 21 - 30"
        menu:
          - href: note/day21.qmd
            text: Day 21
          - href: note/day22.qmd
            text: Day 22

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    # number-sections: true
    smooth-scroll: true
    code-fold: false
    code-tools: false  

execute:
  enabled: false
