project:
  type: website
  output-dir: _site

website:
  title: "算法训练营笔记"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day1.qmd
        text: Day 1

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    code-fold: true
    code-tools: true

execute:
  enabled: false
