project:
  type: website
  output-dir: _site

website:
  title: "算法训练营笔记"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Note"
        menu:
          - href: note/day1.qmd
            text: Day 1
          - href: note/day2.qmd
            text: Day 2
          - href: note/day3.qmd
            text: Day 3
          - href: note/day4.qmd
            text: Day 4
          - href: note/day6.qmd
            text: Day 6
          - href: note/day7.qmd
            text: Day 7
          - href: note/day8.qmd
            text: Day 8
          - href: note/day9.qmd
            text: Day 9

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    # number-sections: true
    smooth-scroll: true
    code-fold: false
    code-tools: false  

execute:
  enabled: false
